### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by merspieler** [merspieler/IDG-A32X#1]
Signed-off-by: merspieler <merspieler@users.noreply.github.com>

_I will document all additions to the property tree with a description below_

#### HYD
* `/systems/hydraulic/ptu-supplies` Indicates which HYD system is supplied by the PTU. Can be `green` , `yellow` or `XX`.
* `/systems/hydraulic/yellow-resv-lo-air-press` Indicates low air pressure in the yellow hyd reservoir. Can be `0` or `1`. _**Note:** This was added as well for the blue and green system._
* `/systems/hydraulic/elec-pump-yellow-ovht` Indicates overheating of the yellow elec pump. Can be `0` or `1`. _**Note:** This was added as well for the blue system._
* `/systems/hydraulic/yellow-resv-ovht` Indicates overheating of too high temperature of the returning hydraulic fluid. Can be `0` or `1`. _**Note:** This was added as well for the blue and green system._
* `/systems/hydraulic/yellow-fire-valve` The fire valve on the engine. Can be `0` or `1`. _**Note:** This was added as well for the green system._
#### BLEED
* `/systems/pneumatic/xbleed-state` describes the state of the xbleed valve, can be `closed`, `open` or `transit`. **Note:** The existing prop `/systems/pneumatic/xbleed` is traded in the display as the manually or automatically **commanded** state
* `/systems/pneumatic/hp-valve-1-state` describes the state of the hp valve, can be `0` or `1`. _* *Note:** this exists as well for the second side._
* `/systems/pneumatic/hp-valve-1` It's the commanded position of the valve, can be `0` or `1`. _* *Note:** this exists as well for the second side._
* `/systems/pneumatic/eng-valve-1-state` describes the state of the eng bleed valve, can be `0` or `1`. _* *Note:** this exists as well for the second side._
* `/systems/pneumatic/eng-valve-1` It's the commanded position of the valve, can be `0` or `1`. _* *Note:** this exists as well for the second side._
* `/systems/pneumetic/precooler-1-psi` The pressure on the inlet of the precooler. _**Note:** this exists as well for the other side._
* `/systems/pneumetic/precooler-1-temp` The temperature on the outlet of the precooler. _**Note:** this exists as well for the other side._
* `/systems/pneumetic/precooler-1-ovht` Indicates that the outlet temperature is too hot, can be `0` or `1`. _**Note:** this exists as well for the other side._
Too hot is when the temerature is:
  * above 290 °C for more than 5 seconds, or
  * above 270 °C for more than 15 seconds, or
  * above 257 °C for more than 55 seconds
* `/systems/pressurization/pack-1-out-temp` The outlet temperature of pack 1.  _**Note:** this exists as well for the other side._
* `/systems/pressurization/pack-1-bypass` The state of the bypass valve. Can be in the range between `0` (fully closed) to `100` (fully open).  _**Note:** this exists as well for the other side._
* `/systems/pressurization/pack-1-comp-out-temp` The Pack Compressor Outlet Temperature.  _**Note:** this exists as well for the other side._
* `/systems/pressurization/pack-1-flow` The Pack flow. Can be in the range between `0` (fully closed) to `100` (fully open).  _**Note:** this exists as well for the other side._
* `/systems/pressurization/pack-1-valve` State of the pack flow valve.   _**Note:** this exists as well for the other side._
#### HYD
* [ ] RAT stowing pressure applied or RAT pump not avail resulting in amber RAT label and arrow
* [ ] HYD reservoir quantity isn't displayed
#### BLEED
* [ ] Wing Anti Ice arrow gets yellow if the _valve_ is open for more than 10 seconds on ground.
* [ ] APU BLEED valve
* [ ] RAM AIR inlet
### Things that needed to be fixed
* [ ] `/systems/hydraulics/ptu-active` isn't constantly `1` when the PTU is active.
* [ ] Some lines, needles and valves on the hyd and bleed page are not completly in solid amber when they are set to amber.
* [ ] Seperated wing anti ice valves for left and right side. **ATTENTION** when done, there are changes to make on the LECAM logic.
* [ ] Seperated psi props for each side before the packs.
* [ ] The bypass valve scale for the packs has to be redesigned.
### Checklist:

* [x] My changes follow the Contributing Guidelines. 
* [x] My changes implement realistic features. 
* [x] Please have an IDG Developer test my changes before merging. 
* [x] My changes are ready for merging.
